mod_name=DynamicTreesBOP
mod_id=dtbop
mod_version=3.4.0
mod_group_id=therealeststu.dtbop
mod_authors=mangoose, Max Hyper

minecraft_version=26.1.2
neo_version=26.1.2.76

dynamicTreesVersion=1.8.0-BETA03
dynamicTreesPlusVersion=1.3.0-BETA04
bopVersion=26.1.2.0.22
glitchCoreVersion=26.1.2.0.2

versionType=stable
versionRecommended=true
updateCheckerPath=Add-ons/BOP.json

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
